/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

DROP TABLE IF EXISTS `bindings`;
CREATE TABLE `bindings` (
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`binding` VARCHAR(32) NOT NULL UNIQUE	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`isbn` VARCHAR(20) NOT NULL UNIQUE,
	`title` VARCHAR(1000) NOT NULL,
	`publisher` VARCHAR(100) DEFAULT NULL,
	`published_on` DATE DEFAULT NULL,
	`language` VARCHAR(20) DEFAULT NULL,
	`price` DECIMAL(7,4) DEFAULT NULL,
	`vat` INT DEFAULT NULL,
	`mediatype` VARCHAR(20) DEFAULT NULL,
	`binding_id` INT DEFAULT NULL,
	`distributor_name` VARCHAR(100) DEFAULT NULL,
	`catalog_text` MEDIUMTEXT DEFAULT NULL,
	`saga` MEDIUMTEXT DEFAULT NULL,
	`num_pages` INT DEFAULT NULL,
	`width` INT DEFAULT NULL,
	`height` INT DEFAULT NULL,
	`length` INT DEFAULT NULL,
	FOREIGN KEY (`binding_id`) REFERENCES `bindings`(`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `authors`;
CREATE TABLE IF NOT EXISTS `authors` (
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`author` VARCHAR(100) NOT NULL UNIQUE	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `product_authors`;
CREATE TABLE IF NOT EXISTS `product_authors` (
	`product_id` INT NOT NULL,
	`author_id` INT NOT NULL,
	PRIMARY KEY (`product_id`, `author_id`),
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`author_id`) REFERENCES `authors`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
